name: sync all public
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 4,16 * * *'
  # - cron: '0 */6 * * *'

jobs:
  SyncBot:
    runs-on: ubuntu-latest
    env:
      ___X_CMD_GHACTION_X: x2
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY_FOR_SYNC }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        timeout-minutes: 8
        with:
          code: xws action/sync || exit
